# Generated by Django 5.0.1 on 2025-11-24 10:40

import django.core.validators
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLATemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('response_time', models.IntegerField(help_text='Response time in hours')),
                ('resolution_time', models.IntegerField(help_text='Resolution time in hours')),
                ('high_priority_response', models.IntegerField(default=2, help_text='High priority response time in hours')),
                ('high_priority_resolution', models.IntegerField(default=24, help_text='High priority resolution time in hours')),
                ('medium_priority_response', models.IntegerField(default=4, help_text='Medium priority response time in hours')),
                ('medium_priority_resolution', models.IntegerField(default=48, help_text='Medium priority resolution time in hours')),
                ('low_priority_response', models.IntegerField(default=8, help_text='Low priority response time in hours')),
                ('low_priority_resolution', models.IntegerField(default=72, help_text='Low priority resolution time in hours')),
                ('department_id', models.UUIDField(blank=True, db_index=True, help_text='Specific department, null for global', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'SLA Template',
                'verbose_name_plural': 'SLA Templates',
                'db_table': 'sla_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['department_id'], name='sla_templat_departm_a5fffd_idx'), models.Index(fields=['is_active'], name='sla_templat_is_acti_b5ad91_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', django_fsm.FSMField(db_index=True, default='assigned', max_length=50, protected=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20)),
                ('parent_ticket_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(db_index=True)),
                ('assignee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('version', models.IntegerField(default=1)),
                ('reopen_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sub Ticket',
                'verbose_name_plural': 'Sub Tickets',
                'db_table': 'sub_tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent_ticket_id'], name='sub_tickets_parent__112c49_idx'), models.Index(fields=['status'], name='sub_tickets_status_45a1fb_idx'), models.Index(fields=['department_id'], name='sub_tickets_departm_ef380b_idx'), models.Index(fields=['assignee_id'], name='sub_tickets_assigne_f02df1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', django_fsm.FSMField(db_index=True, default='draft', max_length=50, protected=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('requestor_id', models.UUIDField(db_index=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('assignee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('reopen_count', models.IntegerField(default=0)),
                ('requires_approval', models.BooleanField(default=False)),
                ('postponement_reason', models.TextField(blank=True)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_status_fbbf05_idx'), models.Index(fields=['requestor_id'], name='tickets_request_113b07_idx'), models.Index(fields=['department_id'], name='tickets_departm_f04f72_idx'), models.Index(fields=['assignee_id'], name='tickets_assigne_e810be_idx'), models.Index(fields=['is_deleted', 'status'], name='tickets_is_dele_a268d6_idx'), models.Index(fields=['created_at'], name='tickets_created_ed60df_idx')],
            },
        ),
    ]
