# Generated by Django 5.0.1 on 2025-12-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_request_0ad5aa_idx',
            old_name='tickets_request_113b07_idx',
        ),
    ]
