# Generated by Django 5.0.1 on 2025-12-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
