# Generated by Django 5.0.1 on 2025-11-24 10:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('requestor', 'requestor'), ('moderator', 'Moderator'), ('assignee', 'Assignee'), ('admin', 'Admin')], db_index=True, default='requestor', max_length=20)),
                ('is_ceo', models.BooleanField(db_index=True, default=False)),
                ('helpdesk_authorized', models.BooleanField(default=False)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('sms_user_id', models.IntegerField(blank=True, null=True)),
                ('last_sms_sync', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['employee_code'], name='users_employe_ac6b2f_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['department_id'], name='users_departm_5a2d9a_idx'), models.Index(fields=['is_deleted', 'role'], name='users_is_dele_a5eaf9_idx')],
            },
        ),
    ]
